//! 剪贴板：监听、多格式读取、写入、整份备份/恢复（规格 05 §1）。
//!
//! macOS 的剪贴板没有变化通知，只能盯着 `changeCount`（每次内容被换掉就加一）轮询。
//! 它就是上层说的"序列号"。
//!
//! 图片在 macOS 的剪贴板里一般是 TIFF 或 PNG，统一交给 `NSBitmapImageRep` 解码，再转成 sRGB。

use std::path::PathBuf;
use std::sync::mpsc::Sender;
use std::sync::OnceLock;
use std::time::Duration;

use image::RgbaImage;
use objc2::rc::{autoreleasepool, Retained};
use objc2::runtime::AnyObject;
use objc2::{msg_send, AnyThread};
use objc2_app_kit::{NSBitmapImageRep, NSPasteboard, NSPasteboardItem, NSWorkspace};
use objc2_foundation::{NSArray, NSData, NSString, NSURL};

use super::util::{self, encode_handle};
use super::window_enum;
use crate::error::{AppError, AppResult};
use crate::platform::{AppInfo, ClipboardPayload, ClipboardSnapshot, WindowHandle};

const TYPE_TEXT: &str = "public.utf8-plain-text";
const TYPE_HTML: &str = "public.html";
const TYPE_RTF: &str = "public.rtf";
const TYPE_PNG: &str = "public.png";
const TYPE_TIFF: &str = "public.tiff";
const TYPE_JPEG: &str = "public.jpeg";
const TYPE_HEIC: &str = "public.heic";
/// 通用剪贴板：内容是从同一个 Apple 账号的 iPhone / iPad / 另一台 Mac 上复制过来的。
/// 系统不告诉是哪台设备、哪个应用
const TYPE_REMOTE: &str = "com.apple.is-remote-clipboard";
/// iPhone / iPad 的「照片」复制时带上的照片 ID：有它就知道是从相册复制的
const TYPE_IOS_PHOTOS: &str = "com.apple.mobileslideshow.asset.localidentifier";
/// 用 Mac 上的「照片」当来源图标
const PHOTOS_APP: &str = "/System/Applications/Photos.app";
const TYPE_FILE_URL: &str = "public.file-url";

/// 应用用这些类型标记"别记进剪贴板历史"（nspasteboard.org 的约定，密码管理器都遵守）
const PRIVACY_TYPES: [&str; 4] = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
];

const POLL_INTERVAL: Duration = Duration::from_millis(200);
/// 单份备份的大小上限，超过就不备份（划词翻译后不恢复，好过卡住）。
const MAX_BACKUP_BYTES: usize = 64 * 1024 * 1024;

static SENDER: OnceLock<Sender<ClipboardSnapshot>> = OnceLock::new();

fn pasteboard() -> Retained<NSPasteboard> {
    NSPasteboard::generalPasteboard()
}

fn ns(text: &str) -> Retained<NSString> {
    NSString::from_str(text)
}

pub fn sequence_number() -> u32 {
    pasteboard().changeCount() as u32
}

// ───────────────────────── 监听 ─────────────────────────

pub fn start_listener(tx: Sender<ClipboardSnapshot>) -> AppResult<()> {
    if SENDER.set(tx).is_err() {
        return Err(AppError::msg("剪贴板监听已经启动"));
    }
    std::thread::Builder::new()
        .name("clipboard-listener".into())
        .spawn(listener_thread)?;
    Ok(())
}

fn listener_thread() {
    let mut last = sequence_number();
    loop {
        std::thread::sleep(POLL_INTERVAL);
        autoreleasepool(|_| {
            let mut now = sequence_number();
            if now == last {
                return;
            }
            // 先同步记下来源应用，再等内容写完：很多程序是先清空、再分几步写入
            let source = NSWorkspace::sharedWorkspace()
                .frontmostApplication()
                .and_then(|app| {
                    window_enum::app_info_of(WindowHandle(encode_handle(
                        app.processIdentifier(),
                        0,
                    )))
                });
            for _ in 0..5 {
                std::thread::sleep(Duration::from_millis(30));
                let again = sequence_number();
                if again == now {
                    break;
                }
                now = again;
            }
            last = now;
            let Some(tx) = SENDER.get() else { return };
            let mut snapshot = read_snapshot();
            // 通用剪贴板过来的：前台应用和它没关系（认得出的应用 read_snapshot 里已经填了）
            if !snapshot.from_other_device {
                snapshot.source = source;
            }
            snapshot.sequence = now;
            let _ = tx.send(snapshot);
        });
    }
}

// ───────────────────────── 读取 ─────────────────────────

fn has_type(types: &[String], wanted: &str) -> bool {
    types.iter().any(|t| t == wanted)
}

fn read_files(pb: &NSPasteboard) -> Vec<PathBuf> {
    let Some(items) = pb.pasteboardItems() else {
        return Vec::new();
    };
    let file_type = ns(TYPE_FILE_URL);
    items
        .iter()
        .take(500)
        .filter_map(|item| {
            let text = item.stringForType(&file_type)?;
            let url = NSURL::URLWithString(&text)?;
            // 访达给的可能是"文件引用"地址（file:///.file/id=…），先换成路径地址
            let url = url.filePathURL().unwrap_or(url);
            Some(PathBuf::from(url.path()?.to_string()))
        })
        .collect()
}

/// 剪贴板里给的是系统临时位置的一张图片文件：其实是"复制了一张图"，不是复制了一个文件。
/// - iPhone / iPad 上复制的图片（通用剪贴板）落在
///   `~/Library/Group Containers/group.com.apple.coreservices.useractivityd/shared-pasteboard/…`
/// - 输入法（微信输入法）、一些应用复制图片时也是先写到自己的缓存目录再放文件地址
///
/// 这些文件过一会儿就被系统删掉，按文件记的话卡片没有预览，之后也粘贴不出来。
/// 访达里复制的图片文件不在这些位置，照旧按文件记。
fn is_temp_image(path: &std::path::Path) -> bool {
    const IMAGE_EXT: [&str; 10] = [
        "png", "jpg", "jpeg", "heic", "heif", "tif", "tiff", "webp", "bmp", "avif",
    ];
    let ext_ok = path
        .extension()
        .and_then(|e| e.to_str())
        .is_some_and(|e| IMAGE_EXT.contains(&e.to_ascii_lowercase().as_str()));
    if !ext_ok {
        return false;
    }
    let home = std::env::var_os("HOME")
        .map(PathBuf::from)
        .unwrap_or_default();
    let temp_roots = [
        home.join("Library/Caches"),
        home.join("Library/Group Containers"),
        home.join("Library/Containers"),
        PathBuf::from("/private/var/folders"),
        PathBuf::from("/var/folders"),
        PathBuf::from("/private/tmp"),
        PathBuf::from("/tmp"),
    ];
    temp_roots.iter().any(|root| path.starts_with(root))
}

/// 读临时图片文件放进 `snap.image`。PNG 留原字节（透明度），正着的 JPEG 也留原字节（省空间）；
/// HEIC 之类交给系统解码。
fn load_temp_image(path: &std::path::Path, snap: &mut ClipboardSnapshot) -> bool {
    const MAX_BYTES: u64 = 64 * 1024 * 1024;
    if std::fs::metadata(path).map_or(true, |m| m.len() > MAX_BYTES) {
        return false;
    }
    let Ok(bytes) = std::fs::read(path) else {
        return false;
    };
    let is_png = bytes.starts_with(&[0x89, b'P', b'N', b'G']);
    let is_jpeg = bytes.starts_with(&[0xFF, 0xD8, 0xFF]);
    if is_jpeg {
        return take_jpeg(bytes, snap);
    }
    if is_png {
        let Ok((img, _)) = crate::imaging::decode_upright(&bytes) else {
            return false;
        };
        snap.image = Some(img);
        snap.image_png = Some(bytes);
        return true;
    }
    snap.image = decode_image(&NSData::with_bytes(&bytes));
    snap.image.is_some()
}

/// 照片（JPEG）：按 EXIF 方向摆正。存的时候也用 JPEG —— 转成 PNG 的话一张 1200 万像素的
/// 手机照片有 60–80MB，超过历史的图片大小上限就存不下了。正着的直接留原字节。
fn take_jpeg(bytes: Vec<u8>, snap: &mut ClipboardSnapshot) -> bool {
    let Ok((img, upright)) = crate::imaging::decode_upright(&bytes) else {
        return false;
    };
    snap.image_jpeg = if upright {
        Some(bytes)
    } else {
        crate::imaging::encode_jpeg(&img, 92).ok()
    };
    snap.image = Some(img);
    true
}

/// PNG / TIFF 数据 → RGBA。
fn decode_image(data: &NSData) -> Option<RgbaImage> {
    let rep = NSBitmapImageRep::imageRepWithData(data)?;
    let (w, h) = (rep.pixelsWide(), rep.pixelsHigh());
    if w <= 0 || h <= 0 {
        return None;
    }
    let cg = rep.CGImage()?;
    util::rgba_from_cgimage(
        Retained::as_ptr(&cg).cast_mut().cast(),
        w as u32,
        h as u32,
        false,
    )
}

fn read_snapshot() -> ClipboardSnapshot {
    let pb = pasteboard();
    let mut snap = ClipboardSnapshot::default();
    let types: Vec<String> = pb
        .types()
        .map(|t| t.iter().map(|s| s.to_string()).collect())
        .unwrap_or_default();
    snap.privacy_flagged = PRIVACY_TYPES.iter().any(|p| has_type(&types, p));
    snap.from_other_device = has_type(&types, TYPE_REMOTE);
    // 通用剪贴板一般认不出是哪个应用复制的，相册是例外
    if snap.from_other_device && has_type(&types, TYPE_IOS_PHOTOS) {
        snap.source = Some(AppInfo {
            name: crate::i18n::text("照片"),
            exe_path: Some(PathBuf::from(PHOTOS_APP)).filter(|p| p.exists()),
        });
    }

    if has_type(&types, TYPE_FILE_URL) {
        snap.files = read_files(&pb);
        if let [one] = snap.files.as_slice() {
            let one = one.clone();
            if is_temp_image(&one) && load_temp_image(&one, &mut snap) {
                snap.files.clear();
            }
        }
    }
    if has_type(&types, TYPE_TEXT) {
        snap.text = pb.stringForType(&ns(TYPE_TEXT)).map(|s| s.to_string());
    }
    if has_type(&types, TYPE_HTML) {
        snap.html = pb.stringForType(&ns(TYPE_HTML)).map(|s| s.to_string());
    }
    if has_type(&types, TYPE_RTF) {
        snap.rtf = pb
            .dataForType(&ns(TYPE_RTF))
            .map(|d| String::from_utf8_lossy(&d.to_vec()).into_owned());
    }
    // 复制文件时访达会顺带放一张文件图标，那不是用户要的图片
    if snap.files.is_empty() {
        if has_type(&types, TYPE_PNG) {
            if let Some(data) = pb.dataForType(&ns(TYPE_PNG)) {
                snap.image = decode_image(&data);
                if snap.image.is_some() {
                    snap.image_png = Some(data.to_vec());
                }
            }
        }
        // iPhone 通用剪贴板过来的照片常常直接带 JPEG / HEIC 数据
        if snap.image.is_none() && has_type(&types, TYPE_JPEG) {
            if let Some(data) = pb.dataForType(&ns(TYPE_JPEG)) {
                take_jpeg(data.to_vec(), &mut snap);
            }
        }
        if snap.image.is_none() && has_type(&types, TYPE_HEIC) {
            snap.image = pb
                .dataForType(&ns(TYPE_HEIC))
                .and_then(|d| decode_image(&d));
        }
        if snap.image.is_none() && has_type(&types, TYPE_TIFF) {
            snap.image = pb
                .dataForType(&ns(TYPE_TIFF))
                .and_then(|d| decode_image(&d));
        }
    }
    snap
}

pub fn read_text() -> Option<String> {
    autoreleasepool(|_| {
        pasteboard()
            .stringForType(&ns(TYPE_TEXT))
            .map(|s| s.to_string())
    })
}

// ───────────────────────── 写入 ─────────────────────────

/// RGBA → TIFF。不压缩，4K 截图也只是一次内存拷贝，"复制"才能立刻完成；
/// macOS 上的程序（包括浏览器、微信、Office）都认 TIFF。
fn encode_tiff(image: &RgbaImage) -> AppResult<Retained<NSData>> {
    let cg = util::cgimage_from_rgba(image, false).ok_or_else(|| AppError::msg("图片转换失败"))?;
    // SAFETY: cg 是有效的 CGImage，rep 创建时会持有它。
    let rep = unsafe {
        NSBitmapImageRep::initWithCGImage(NSBitmapImageRep::alloc(), &*cg.0.cast_const().cast())
    };
    rep.TIFFRepresentation()
        .ok_or_else(|| AppError::msg("图片编码失败"))
}

fn write_objects(pb: &NSPasteboard, objects: &[&AnyObject]) -> bool {
    let array = NSArray::from_slice(objects);
    // SAFETY: 数组里是 NSURL / NSPasteboardItem，都实现了 NSPasteboardWriting。
    unsafe { msg_send![pb, writeObjects: &*array] }
}

pub fn write(payload: &ClipboardPayload) -> AppResult<()> {
    autoreleasepool(|_| {
        let pb = pasteboard();
        let ok = match payload {
            ClipboardPayload::Text { text, html, rtf } => {
                pb.clearContents();
                let mut ok = pb.setString_forType(&ns(text), &ns(TYPE_TEXT));
                if let Some(html) = html {
                    ok &= pb.setString_forType(&ns(html), &ns(TYPE_HTML));
                }
                if let Some(rtf) = rtf {
                    ok &= pb
                        .setData_forType(Some(&NSData::with_bytes(rtf.as_bytes())), &ns(TYPE_RTF));
                }
                ok
            }
            ClipboardPayload::Image { image, png } => {
                // 编码在清空剪贴板之前做完
                let tiff = encode_tiff(image)?;
                pb.clearContents();
                let mut ok = true;
                if let Some(png) = png {
                    ok &= pb.setData_forType(Some(&NSData::with_bytes(png)), &ns(TYPE_PNG));
                }
                ok & pb.setData_forType(Some(&tiff), &ns(TYPE_TIFF))
            }
            ClipboardPayload::Files(files) => {
                let urls: Vec<Retained<NSURL>> = files
                    .iter()
                    .map(|f| NSURL::fileURLWithPath(&ns(&f.to_string_lossy())))
                    .collect();
                let refs: Vec<&AnyObject> = urls.iter().map(|u| -> &AnyObject { u }).collect();
                pb.clearContents();
                write_objects(&pb, &refs)
            }
        };
        if ok {
            Ok(())
        } else {
            Err(AppError::msg("写入剪贴板失败"))
        }
    })
}

// ───────────────────────── 备份 / 恢复 ─────────────────────────

/// 每个条目的全部（类型，数据）。
pub type Backup = Vec<Vec<(String, Vec<u8>)>>;

pub fn backup() -> Option<Backup> {
    autoreleasepool(|_| {
        let pb = pasteboard();
        let mut out = Vec::new();
        let mut total = 0usize;
        for item in pb.pasteboardItems()?.iter() {
            let mut entries = Vec::new();
            for kind in item.types().iter() {
                let Some(data) = item.dataForType(&kind) else {
                    continue;
                };
                total += data.length();
                if total > MAX_BACKUP_BYTES {
                    return None;
                }
                entries.push((kind.to_string(), data.to_vec()));
            }
            out.push(entries);
        }
        Some(out)
    })
}

pub fn restore(backup: Backup) {
    autoreleasepool(|_| {
        let pb = pasteboard();
        pb.clearContents();
        let items: Vec<Retained<NSPasteboardItem>> = backup
            .iter()
            .filter(|entries| !entries.is_empty())
            .map(|entries| {
                let item = NSPasteboardItem::new();
                for (kind, bytes) in entries {
                    item.setData_forType(&NSData::with_bytes(bytes), &ns(kind));
                }
                item
            })
            .collect();
        if items.is_empty() {
            return;
        }
        let refs: Vec<&AnyObject> = items.iter().map(|i| -> &AnyObject { i }).collect();
        if !write_objects(&pb, &refs) {
            tracing::debug!("恢复剪贴板失败");
        }
    });
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn temp_image_files_are_images() {
        let home = PathBuf::from(std::env::var_os("HOME").unwrap());
        let iphone = home.join(
            "Library/Group Containers/group.com.apple.coreservices.useractivityd/shared-pasteboard/items/X/IMG_6359.jpeg",
        );
        assert!(is_temp_image(&iphone));
        assert!(is_temp_image(
            &home.join("Library/Caches/WeType/dsclp/1.png")
        ));
        assert!(is_temp_image(std::path::Path::new(
            "/private/var/folders/ab/T/x.HEIC"
        )));
        // 访达里复制的图片文件、临时目录里的非图片：照旧是文件
        assert!(!is_temp_image(&home.join("Pictures/IMG_6359.jpeg")));
        assert!(!is_temp_image(std::path::Path::new(
            "/Volumes/Extreme SSD/a.png"
        )));
        assert!(!is_temp_image(&home.join("Library/Caches/x.zip")));
        assert!(!is_temp_image(&home.join("Library/Caches/x.gif")));
    }

    #[test]
    fn tiff_roundtrip() {
        let mut img = RgbaImage::new(3, 2);
        img.put_pixel(0, 0, image::Rgba([255, 0, 0, 255]));
        img.put_pixel(2, 1, image::Rgba([0, 0, 255, 255]));
        let tiff = encode_tiff(&img).unwrap();
        let decoded = decode_image(&tiff).unwrap();
        assert_eq!(decoded.dimensions(), (3, 2));
        assert_eq!(decoded.get_pixel(0, 0), &image::Rgba([255, 0, 0, 255]));
        assert_eq!(decoded.get_pixel(2, 1), &image::Rgba([0, 0, 255, 255]));
        assert_eq!(decoded.get_pixel(1, 1)[3], 0);
    }
}
